### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by Billabongodysee** [markstan/IntuneOneDataCollector#1]
wget https://aka.ms/intunexml -outfile Intune.xml
     wget https://aka.ms/intuneps1 -outfile IntuneODCStandAlone.ps1
     PowerShell -ExecutionPolicy Bypass -File .\IntuneODCStandAlone.ps1

Why am I calling PowerShell if I've already opened an elevated Powershell prompt like the directions say? "PowerShell -ExecutionPolicy Bypass -File .\IntuneODCStandAlone.ps1" 

I get multiple errors telling me things like "Unexpected token '-getfiles' in expression or statement
OR
The '<' operator is reserved for future use   line 894, char:80

**Comment by markstan** [comment]
Hi @Billabongodysee - thanks for the report.  I've actually seen this before.  You get that if you don't change the URL for the second command.  The "The '<' operator is reserved for future use." error means you're trying to execute an XML document as PowerShell.

> Why am I calling PowerShell if I've already opened an elevated Powershell prompt like the directions say? 
It's a more repeatable experience (we see a lot of test devices and workstations where PS has never been  ran interactively).  We tell people to do that so I don't have to worry about permanently changing the ExecutionPolicy or otherwise making changes to the system.  If your ExectionPolicy already allows scripts to run, you can just run .\IntuneODCStandAlone.ps1 by itself.

I'll document the error in the project.  Thanks again for the heads-up.

HTH,
Mark
